# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Diagonal Quadratic Form
#'
#' Calculates the matrix \eqn{Z'WZ}, where \eqn{W} is a diagonal
#' matrix. 
#'
#' @param Z Design matrix.
#' @param w Weight vector.
#' @return Numeric matrix. 
#' @export 
#'
diagQF <- function(Z, w) {
    .Call('_Probit_diagQF', PACKAGE = 'Probit', Z, w)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
fastDet <- function(A) {
    .Call('_Probit_fastDet', PACKAGE = 'Probit', A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
fastIP <- function(A, B) {
    .Call('_Probit_fastIP', PACKAGE = 'Probit', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
fastInv <- function(A) {
    .Call('_Probit_fastInv', PACKAGE = 'Probit', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
fastMMp <- function(A, B) {
    .Call('_Probit_fastMMp', PACKAGE = 'Probit', A, B)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
tr <- function(A) {
    .Call('_Probit_tr', PACKAGE = 'Probit', A)
}

#' Matrix Transpose
#'
#' Constructs \eqn{A'} from \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix.
fastT <- function(A) {
    .Call('_Probit_fastT', PACKAGE = 'Probit', A)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix.
fastQF <- function(X, A) {
    .Call('_Probit_fastQF', PACKAGE = 'Probit', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{11}-I_{12}I_{22}^{-1}I_{21}}. 
#'
#' @param I11 Information of target parameter
#' @param I22 Information of nuisance parameter
#' @param I12 Cross information between target and nuisance parameters
#' @return Numeric matrix. 
#' @export 
#'
SchurC <- function(I11, I22, I12) {
    .Call('_Probit_SchurC', PACKAGE = 'Probit', I11, I22, I12)
}

#' Weighted Least Squares
#'
#' Estimates the weighted least squares coefficient 
#' \deqn{\hat{\beta}=(Z'WZ)^{-1}Z'Wy}
#' 
#' The weight matrix is assumed diagonal, and is supplied
#' as a vector. 
#'
#' @param Z Design matrix.
#' @param w Weight vector.
#' @param y Response vector.
#' @return Numeric vector. 
#' @export 
#'
WLS <- function(Z, w, y) {
    .Call('_Probit_WLS', PACKAGE = 'Probit', Z, w, y)
}

#' Ordiary Least Squares
#'
#' Estimates the ordinary least squares coefficient 
#' \deqn{\hat{\beta}=(Z'Z)^{-1}Z'y}
#'
#' @param Z Design matrix.
#' @param y Response vector.
#' @return Numeric vector. 
#' @export 
#'
OLS <- function(Z, y) {
    .Call('_Probit_OLS', PACKAGE = 'Probit', Z, y)
}

